### ISSUE TITLE
Defining Data

### ISSUE THREAD

**Issue by fergusleen** [maziac/z80dismblr#8]
Hi, I'm using this interesting disassembler to disassemble an Amstrad CPC ROM. I can't seem to find a way to define data areas that are being marked up as code. Am I missing something?

**Comment by maziac** [comment]
Hi,
for z80dismblr at the start everything is data.
I.e. it is vice versa. If z80dismblr recognizes that some area is used as code it is marked as code.
Can you maybe share the code and the arguments you used?

**Comment by fergusleen** [comment]
Thanks for the reply and the explanation.

I've attached the files I'm working with. I've left out the large mame trace files.

Here's an example in the command table : - 
(c000 start)
```
C04D 48           defb 48h    	; 72, 'H'
C04E 4F           defb 4Fh    	; 79, 'O'
C04F 4E           defb 4Eh    	; 78, 'N'
C050 45           defb 45h    	; 69, 'E'
C051 59           defb 59h    	; 89, 'Y'
C052 54           defb 54h    	; 84, 'T'
C053 45           defb 45h    	; 69, 'E'
C054 52           defb 52h    	; 82, 'R'
C055 CD           defb CDh    	; 205,  -51
C056 48           defb 48h    	; 72, 'H'
C057 D4           defb D4h    	; 212,  -44


; Subroutine: Size=90, CC=10.
; Called by: -
; Calls: SUB003, SUB004, SUB005, SUB006, SUB007, SUB009, SUB011, SUB012, SUB013, COMMSTAR_RSX.
C058 INTRPT14:
C058 43           ld   b,e    ;C
C059 4F           ld   c,a    ;O 
C05A 50           ld   d,b   ; P 
C05B 45           ld   b,l    ;E
C05C CE 43        adc  a,43h  	; 67, 'C'      ;N +&80, C
C05E 43           ld   b,e    ;C
C05F 4C           ld   c,h    ;L
C060 4F           ld   c,a    ;O ...
C061 53           ld   d,e    
C062 C5           push bc     
C063 43           ld   b,e    
C064 50           ld   d,b    
C065 55           ld   d,l    
```
This should continue as data ( C O P E (N+&80)) rather than start a sub routine. Adding the &80 signifies the end of the current string. 

Thanks for your help,


[cpccommsrom_disasm.zip](https://github.com/maziac/z80dismblr/files/6448253/cpccommsrom_disasm.zip)

**Comment by maziac** [comment]
Could you please attach the full name trace file (zipped). It could be that it contains these addresses for whatever reason.
C058 is not called by the code itself ("Called by: -"), i.e. it must come from the outside.

**Comment by fergusleen** [comment]
Trace file attached. I'm wondering if this could be due to the CPC swapping the ROM in and out of 0xc000 with the screen mem ram?

[ht2.tr.zip](https://github.com/maziac/z80dismblr/files/6448359/ht2.tr.zip)

**Comment by maziac** [comment]
Here you have it:
![Bildschirmfoto 2021-05-09 um 22 38 56](https://user-images.githubusercontent.com/3081973/117586270-75951200-b117-11eb-8118-8181f7721e98.jpg)
The trace file contains the C058 address. I.e. the PC has gone there.
z80dismblr does not care about the opcode in the trace file, it only reads the addresses.

Now the question is: why is there a trace at that address? Obviously the executed code is not what you  see there. There are several possibilities:
a) the trace is wrong, i.e. from different code
b) the area was overwritten. i.e. the machine code was copied later to address C058 (can't be if it is really ROM)
c) the CPU trace is from another CPU (MAME simulates more than one CPU, e.g. if there are separate CPUs for sound or graphics)
d) the start address of the rom is wrong
e) there is some banking mechanism in place, i.e. the original bank was exchanged with another bank

**Comment by maziac** [comment]
One more interesting thing:
From the trace you see that SP is loaded with C000.
But C000 should be ROM.
I.e. this does not make much sense.

**Comment by fergusleen** [comment]
Thank you. I think most likely is that the disc rom was swapped in. 

From CPCWIKI:
The CPC can choose which ROM chip is associated with the 16K area starting at &C000. This is usually the reserved for the contents of the screen (RAM), but the address range is shared with ROM Memory.

Now to find a way to remove that from the trace file..!

Thanks again for helping me with this, and for this software.

**Comment by maziac** [comment]
No, problem.
I'm happy that I could help a little bit.
